// Phase A2 — Salesperson narrative report.
//
// Calls POST /api/ai/report, renders the six-section report, shows the numeric
// guard status, and provides a Download PDF button (window.print()).
//
// Architecture: app = numbers. Claude = judgement.
// Every number in the rendered text was checked by the server-side numeric guard
// before reaching this component. If guard.status === "requires_review", an
// orange banner lists the flagged figures.

import { useState } from "react";
import { cn } from "@/lib/utils";

const BASE = import.meta.env.BASE_URL ?? "/";
const API  = `${BASE}api`.replace(/\/\//g, "/");

// ── Types ─────────────────────────────────────────────────────────────────────

interface ReportSection {
  title: string;
  body:  string;
}

interface UnmatchedNumber {
  extracted: string;
  value:     number;
  sentence:  string;
}

interface GuardResult {
  status:    "ok" | "requires_review";
  checked:   number;
  unmatched: UnmatchedNumber[];
}

interface AiReport {
  fy:          string;
  member:      string;
  stateHead:   string | null;
  dataCutoff:  string;
  generatedAt: string;
  sections: {
    executiveSummary:         ReportSection;
    performanceAgainstTarget: ReportSection;
    coverageAndCustomerBase:  ReportSection;
    visitEffectiveness:       ReportSection;
    costAndReturn:            ReportSection;
    risksAndDataCaveats:      ReportSection;
  };
  guard:           GuardResult;
  corruptTestMode?: boolean;
}

// ── Props ─────────────────────────────────────────────────────────────────────

interface Props {
  fy:         string;
  stateHead:  string;
  memberKey:  string;   // normKey
  memberName: string;
}

// ── Guard status badge ────────────────────────────────────────────────────────

function GuardStatusBadge({
  guard,
  corrupt,
}: {
  guard:   GuardResult;
  corrupt: boolean;
}) {
  if (guard.status === "ok" && !corrupt) {
    return (
      <div className="no-print flex items-center gap-2 rounded-md border border-green-600/30 bg-green-50 px-3 py-2 text-sm text-green-800">
        <span className="font-semibold">Numeric guard:</span>
        <span>{guard.checked} tokens checked — zero unmatched. Report is cleared for review.</span>
      </div>
    );
  }

  return (
    <div className="no-print flex flex-col gap-2 rounded-md border border-amber-500/40 bg-amber-50 px-3 py-2 text-sm text-amber-900">
      <div className="flex items-center gap-2">
        <span className="font-semibold">
          {corrupt ? "Guard test — MISMATCH DETECTED (expected)" : "Requires review"}
        </span>
        <span>
          {guard.unmatched.length} of {guard.checked} tokens could not be matched to the payload.
        </span>
      </div>
      {guard.unmatched.length > 0 && (
        <ul className="mt-1 space-y-1 pl-2 border-l-2 border-amber-400">
          {guard.unmatched.map((u, i) => (
            <li key={i} className="text-xs">
              <span className="font-mono font-bold">{u.extracted}</span>
              {" — "}
              <span className="italic">{u.sentence}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// ── Single report section ─────────────────────────────────────────────────────

function Section({ section }: { section: ReportSection }) {
  return (
    <div className="report-section">
      <h2 className="report-section-title">{section.title}</h2>
      <div className="report-section-body">
        {section.body.split("\n\n").map((para, i) => (
          <p key={i} className="report-para">{para}</p>
        ))}
      </div>
    </div>
  );
}

// ── Full printable document ───────────────────────────────────────────────────

function ReportDocument({ report }: { report: AiReport }) {
  const { fy, member, stateHead, dataCutoff, generatedAt, sections } = report;

  const cutoffFmt = new Date(dataCutoff).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

  const generatedFmt = new Date(generatedAt).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit",
  });

  const sectionOrder = [
    sections.executiveSummary,
    sections.performanceAgainstTarget,
    sections.coverageAndCustomerBase,
    sections.visitEffectiveness,
    sections.costAndReturn,
    sections.risksAndDataCaveats,
  ];

  const footerText =
    `Data cutoff: ${cutoffFmt}  |  Generated: ${generatedFmt}  |  ` +
    `Figures computed by Prayag India Sales Intelligence; narrative generated by Claude (Anthropic)`;

  return (
    <div id="printable-report" className="report-document">
      {/* Print CSS — injected inline so it applies when window.print() is called */}
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #printable-report,
          #printable-report * { visibility: visible !important; }
          #printable-report { position: absolute; left: 0; top: 0; width: 100%; }
          .no-print { display: none !important; }
          .report-document {
            font-family: Georgia, "Times New Roman", serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #000;
            padding: 0;
            margin: 0;
          }
          .report-header { border-bottom: 2px solid #000; padding-bottom: 10pt; margin-bottom: 18pt; }
          .report-co-name { font-size: 13pt; font-weight: bold; letter-spacing: 0.04em; text-transform: uppercase; }
          .report-title { font-size: 15pt; font-weight: bold; margin-top: 4pt; }
          .report-meta { font-size: 9pt; color: #444; margin-top: 4pt; }
          .report-section { margin-top: 18pt; page-break-inside: avoid; }
          .report-section-title { font-size: 12pt; font-weight: bold; border-bottom: 1px solid #999; padding-bottom: 3pt; margin-bottom: 8pt; text-transform: uppercase; letter-spacing: 0.03em; }
          .report-section-body { }
          .report-para { margin: 0 0 8pt 0; }
          .report-footer {
            position: fixed;
            bottom: 0; left: 0; right: 0;
            border-top: 1px solid #bbb;
            padding: 5pt 0 0;
            font-size: 7.5pt;
            color: #555;
          }
          @page { margin: 2cm 2cm 3.5cm 2cm; size: A4; }
        }
        @media screen {
          .report-document {
            font-family: ui-serif, Georgia, "Times New Roman", serif;
            font-size: 0.9375rem;
            line-height: 1.7;
            color: #1a1a1a;
            max-width: 700px;
          }
          .report-header {
            border-bottom: 2px solid #1a1a1a;
            padding-bottom: 12px;
            margin-bottom: 20px;
          }
          .report-co-name {
            font-size: 0.7rem;
            font-weight: 700;
            letter-spacing: 0.1em;
            text-transform: uppercase;
            color: #555;
          }
          .report-title {
            font-size: 1.25rem;
            font-weight: 700;
            margin-top: 4px;
          }
          .report-meta {
            font-size: 0.8rem;
            color: #666;
            margin-top: 4px;
          }
          .report-section { margin-top: 24px; }
          .report-section-title {
            font-size: 0.75rem;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            border-bottom: 1px solid #d0d0d0;
            padding-bottom: 4px;
            margin-bottom: 10px;
            color: #333;
          }
          .report-para { margin: 0 0 10px 0; }
          .report-footer { margin-top: 32px; padding-top: 10px; border-top: 1px solid #d0d0d0; font-size: 0.75rem; color: #888; }
        }
      `}</style>

      {/* Header */}
      <div className="report-header">
        <div className="report-co-name">Prayag India Sales Intelligence</div>
        <div className="report-title">Salesperson Performance Report — {member}</div>
        <div className="report-meta">
          {stateHead && <span>State Head: {stateHead}  |  </span>}
          FY {fy}  |  Period: YTD through {cutoffFmt}
        </div>
      </div>

      {/* Sections */}
      {sectionOrder.map((s, i) => (
        <Section key={i} section={s} />
      ))}

      {/* Footer — fixed position in print; normal flow on screen */}
      <div className="report-footer">{footerText}</div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export function SalesPersonReport({ fy, stateHead, memberKey, memberName }: Props) {
  const [report,  setReport]  = useState<AiReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState<string | null>(null);

  async function generate(corrupt = false) {
    setLoading(true);
    setError(null);
    setReport(null);
    try {
      const res = await fetch(`${API}/ai/report`, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ fy, stateHead, member: memberKey, period: "ytd", corrupt }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({})) as Record<string, unknown>;
        throw new Error(typeof body.error === "string" ? body.error : `Server error ${res.status}`);
      }
      const data = await res.json() as AiReport;
      setReport(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Report generation failed.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-3">

      {/* Pre-generate prompt */}
      {!report && !loading && (
        <div className="flex flex-wrap gap-2 items-center no-print">
          <button
            onClick={() => void generate(false)}
            disabled={loading}
            className={cn(
              "h-9 rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground",
              "hover:bg-primary/90 disabled:opacity-50",
            )}
          >
            Generate Report
          </button>
          <button
            onClick={() => void generate(true)}
            disabled={loading}
            title="Injects a wrong figure to prove the guard detects it"
            className={cn(
              "h-9 rounded-md border border-border bg-muted/40 px-4 text-sm",
              "hover:bg-muted/60 disabled:opacity-50",
            )}
          >
            Run Guard Test
          </button>
        </div>
      )}

      {/* Loading */}
      {loading && (
        <div className="rounded-md border border-border bg-muted/30 px-5 py-6 text-sm text-muted-foreground text-center">
          Generating report for {memberName} — this takes 15–30 seconds.
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="rounded-md border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive">
          {error}
        </div>
      )}

      {/* Report actions + document */}
      {report && (
        <div className="space-y-3">

          {/* Action bar */}
          <div className="no-print flex flex-wrap gap-2 items-center">
            <button
              onClick={() => void generate(false)}
              className="h-8 rounded-md border border-border bg-muted/40 px-3 text-xs hover:bg-muted/60"
            >
              Regenerate
            </button>
            <button
              onClick={() => void generate(true)}
              title="Re-run guard test"
              className="h-8 rounded-md border border-border bg-muted/40 px-3 text-xs hover:bg-muted/60"
            >
              Guard Test
            </button>
            <button
              onClick={() => window.print()}
              className={cn(
                "h-8 rounded-md bg-primary px-4 text-xs font-medium text-primary-foreground",
                "hover:bg-primary/90",
              )}
            >
              Download PDF
            </button>
          </div>

          {/* Guard status */}
          <GuardStatusBadge
            guard={report.guard}
            corrupt={report.corruptTestMode ?? false}
          />

          {/* Report */}
          <ReportDocument report={report} />

        </div>
      )}

    </div>
  );
}
