import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analyzeRouter from "./analyze";
import driveRouter from "./drive";
import dashboardRouter from "./dashboard";
import verifyRouter from "./verify";
import analyticsRouter from "./analytics";
import mgmtRouter from "./mgmt";
import targetsRouter from "./targets";
import salespeopleRouter from "./salespeople";
import sapRouter from "./sap";
import auditRouter from "./audit";
import customersRouter from "./customers";
import companyReportsRouter from "./companyReports";
import schemesRouter from "./schemes";
import primaryTargetsRouter from "./primaryTargets";
import primaryStateAchievementRouter from "./primaryStateAchievement";
import primaryVelocityRouter from "./primaryVelocity";
import primaryStateTargetsEditorRouter from "./primaryStateTargetsEditor";
import customerMasterRouter from "./customerMaster";
import apiKeysRouter from "./apiKeys";
import tabDiagnosticRouter from "./tabDiagnostic";
import ordersRouter from "./orders";
import registersRouter from "./registers";
import aiPayloadRouter from "./aiPayload";
import aiReportRouter from "./aiReport";
import aiArtifactsRouter from "./aiArtifacts";
import aiDistributorArtifactsRouter from "./aiDistributorArtifacts";
import aiBatchRouter from "./aiBatch";

const router: IRouter = Router();

router.use(healthRouter);
router.use(analyzeRouter);
router.use(driveRouter);
router.use(dashboardRouter);
router.use(verifyRouter);
router.use(analyticsRouter);
router.use(mgmtRouter);
router.use(targetsRouter);
router.use(salespeopleRouter);
router.use(sapRouter);
router.use(auditRouter);
router.use(customersRouter);
router.use(companyReportsRouter);
router.use(schemesRouter);
router.use(primaryTargetsRouter);
router.use(primaryStateAchievementRouter);
router.use(primaryVelocityRouter);
router.use(primaryStateTargetsEditorRouter);
router.use(customerMasterRouter);
router.use(apiKeysRouter);
router.use(tabDiagnosticRouter);
router.use(ordersRouter);
router.use(registersRouter);
router.use(aiPayloadRouter);
router.use(aiReportRouter);
router.use(aiArtifactsRouter);
router.use(aiDistributorArtifactsRouter);
router.use(aiBatchRouter);

export default router;
