import { Router, type IRouter } from "express";
import { requireServerReady } from "../lib/serverReadiness";
import healthRouter from "./health";
import analyzeRouter from "./analyze";
import driveRouter from "./drive";
import dashboardRouter from "./dashboard";
import verifyRouter from "./verify";
import analyticsRouter from "./analytics";
import mgmtRouter from "./mgmt";
import targetsRouter from "./targets";
import targetEngineRouter from "./targetEngine";
import comparisonRouter from "./comparison";
import salespeopleRouter from "./salespeople";
import sapRouter from "./sap";
import auditRouter from "./audit";
import customersRouter from "./customers";
import companyReportsRouter from "./companyReports";
import regionalReportsRouter from "./regionalReports";
import coverageReportsRouter from "./coverageReports";
import productReportsRouter from "./productReports";
import momentumReportsRouter from "./momentumReports";
import momentumRouter from "./momentum";
import adminUploadsRouter from "./adminUploads";
import schemesRouter from "./schemes";
import primaryTargetsRouter from "./primaryTargets";
import primaryStateAchievementRouter from "./primaryStateAchievement";
import primaryVelocityRouter from "./primaryVelocity";
import primaryStateTargetsEditorRouter from "./primaryStateTargetsEditor";
import customerMasterRouter from "./customerMaster";
import apiKeysRouter from "./apiKeys";
import tabDiagnosticRouter from "./tabDiagnostic";
import ordersRouter from "./orders";
import registersRouter from "./registers";
import aiPayloadRouter from "./aiPayload";
import aiReportRouter from "./aiReport";
import aiArtifactsRouter from "./aiArtifacts";
import aiDistributorArtifactsRouter from "./aiDistributorArtifacts";
import aiBatchRouter from "./aiBatch";
import aiChatRouter from "./aiChat";
import aiFullReportRouter from "./aiFullReport";
import aiGrowthReportRouter from "./aiGrowthReport";
import graphRouter from "./graph";
import warningsRouter from "./warnings";
import orgRouter from "./org";
import masterOrgRouter from "./masterOrg";
import skuRouter from "./sku";
import mrpRouter from "./mrp";
import gpMarginRouter from "./gpMargin";
import stateHierarchyRouter from "./stateHierarchy";
import marketSurveyRouter from "./marketSurvey";
import competitorPriceRouter from "./competitorPrice";
import alertsRouter from "./alerts";

const router: IRouter = Router();

router.use(healthRouter);
// All routes below this line are gated: they return 503 until the post-listen
// background initialisation (person registry, roster CSV restore) completes.
router.use(requireServerReady);
router.use(analyzeRouter);
router.use(driveRouter);
router.use(dashboardRouter);
router.use(verifyRouter);
router.use(analyticsRouter);
router.use(mgmtRouter);
router.use(targetsRouter);
router.use(targetEngineRouter);
router.use(comparisonRouter);
router.use(salespeopleRouter);
router.use(sapRouter);
router.use(auditRouter);
router.use(customersRouter);
router.use(companyReportsRouter);
router.use(regionalReportsRouter);
router.use(coverageReportsRouter);
router.use(productReportsRouter);
router.use(momentumReportsRouter);
router.use(momentumRouter);
router.use(adminUploadsRouter);
router.use(schemesRouter);
router.use(primaryTargetsRouter);
router.use(primaryStateAchievementRouter);
router.use(primaryVelocityRouter);
router.use(primaryStateTargetsEditorRouter);
router.use(customerMasterRouter);
router.use(apiKeysRouter);
router.use(tabDiagnosticRouter);
router.use(ordersRouter);
router.use(registersRouter);
router.use(aiPayloadRouter);
router.use(aiReportRouter);
router.use(aiArtifactsRouter);
router.use(aiDistributorArtifactsRouter);
router.use(aiBatchRouter);
router.use(aiChatRouter);
router.use(aiFullReportRouter);
router.use(aiGrowthReportRouter);
router.use(graphRouter);
router.use(warningsRouter);
router.use(orgRouter);
router.use(masterOrgRouter);
router.use(skuRouter);
router.use(mrpRouter);
router.use(gpMarginRouter);
router.use(stateHierarchyRouter);
router.use(marketSurveyRouter);
router.use(competitorPriceRouter);
router.use(alertsRouter);

export default router;
