// Canonical mapping from primary-state target names to the raw STATE values
// used by the order-book register. Keep this shared by achievement endpoints.
export const STATE_REGISTER_MAP: Record<string, string[]> = {
  "W-BENGAL": ["W-BENGAL"],
  BIHAR: ["BIHAR"],
  JHARKHAND: ["JHARKHAND"],
  ODISHA: ["ODISHA"],
  ASSAM: ["ASSAM"],
  AP: ["AP"],
  Telangana: ["Telangana"],
  "UP(R)": ["UP ( R )"],
  MP: ["MP"],
  "MAHARASTRA R": ["MAHARASTRA R"],
  Chhattisgarh: ["Chhattisgarh"],
  "MAHARASTRA L": ["MAHARASTRA L"],
  Goa: ["Goa"],
  Rajasthan: ["Rajasthan"],
  Haryana: ["Haryana"],
  Uttarakhand: ["Uttarakhand"],
  DELHI: ["DELHI A", "DELHI NCR"],
  "UP(A)": ["UP ( A )"],
  Tamilnadu: ["Tamilnadu"],
  Karnataka: ["Karnataka (B)"],
  Kerala: ["Kerala"],
  PUNJAB: ["PUNJAB"],
  HP: ["HP"],
  KASHMIR: ["KASHMIR"],
  Gujarat: ["Gujarat"],
};